<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

/**
 * Fires at start of header.php, immediately before `genesis_title` action hook to render the Doctype content.
 *
 * @since 1.3.0
 */
do_action( 'genesis_doctype' );

/**
 * Fires immediately after `genesis_doctype` action hook, in header.php to render the document title.
 *
 * @since 1.0.0
 */
do_action( 'genesis_title' );

/**
 * Fires immediately after `genesis_title` action hook, in header.php to render the meta elements.
 *
 * @since 1.0.0
 */
do_action( 'genesis_meta' );

wp_head(); // We need this for plugins.
?>
</head>
<?php
genesis_markup(
	[
		'open'    => '<body %s>',
		'context' => 'body',
	]
);

if ( function_exists( 'wp_body_open' ) ) {
	wp_body_open();
}

/**
 * Fires immediately after the `wp_body_open` action hook.
 *
 * @since 1.0.0
 */
do_action( 'genesis_before' );

genesis_markup(
	[
		'open'    => '<div %s>',
		'context' => 'site-container',
	]
);

/**
 * Fires immediately after the site container opening markup, before `genesis_header` action hook.
 *
 * @since 1.0.0
 */
do_action( 'genesis_before_header' );

/**
 * Fires to display the main header content.
 *
 * @since 1.0.2
 */




	
	$search_svg_m = '<svg width="24" height="24" xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" fill="#fff" clip-rule="evenodd"><path d="M15.853 16.56c-1.683 1.517-3.911 2.44-6.353 2.44-5.243 0-9.5-4.257-9.5-9.5s4.257-9.5 9.5-9.5 9.5 4.257 9.5 9.5c0 2.442-.923 4.67-2.44 6.353l7.44 7.44-.707.707-7.44-7.44zm-6.353-15.56c4.691 0 8.5 3.809 8.5 8.5s-3.809 8.5-8.5 8.5-8.5-3.809-8.5-8.5 3.809-8.5 8.5-8.5z"/></svg>';
	$search_svg_d = '<svg width="24" height="24" xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" fill="#6c757d" clip-rule="evenodd"><path d="M15.853 16.56c-1.683 1.517-3.911 2.44-6.353 2.44-5.243 0-9.5-4.257-9.5-9.5s4.257-9.5 9.5-9.5 9.5 4.257 9.5 9.5c0 2.442-.923 4.67-2.44 6.353l7.44 7.44-.707.707-7.44-7.44zm-6.353-15.56c4.691 0 8.5 3.809 8.5 8.5s-3.809 8.5-8.5 8.5-8.5-3.809-8.5-8.5 3.809-8.5 8.5-8.5z"/></svg>';



	$fieldM = get_term_meta(3, 'pos_menu_m')[0];
	$posM = '';
	switch($fieldM) {
		case 'sx':
			$posM = 'text-start ps-3';
			break;
		case 'dx':
			$posM = 'text-end pe-3';
			break;
	}
	// Button active search
	$searchM = '<div class="my-extra mob position-relative p-0 py-3 bdr-y '. $posM .'">
					<div class="open-search d-inline" data-bs-toggle="modal" data-bs-target="#searchModal">
						'. $search_svg_m .'
					</div>
				</div>';
	$searchD = '<div class="my-extra desk position-relative col-1 text-center">
					<div class="open-search d-inline-block ms-auto" data-bs-toggle="modal" data-bs-target="#searchModal">
						'. $search_svg_d .'
					</div>
				</div>';

	// Modale search
	$modal = '<div class="modal fade" id="searchModal" tabindex="-1" aria-labelledby="searchModalLabel" aria-hidden="true">
					<div class="modal-dialog modal-dialog-centered">
						<div class="modal-content position-relative position-relative">
							<div class="dismiss-icon text-end mb-5" data-bs-dismiss="modal">
								<svg clip-rule="evenodd" fill="#6c757d" width="30" fill-rule="evenodd" stroke-linejoin="round" stroke-miterlimit="2" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="m12 10.93 5.719-5.72c.146-.146.339-.219.531-.219.404 0 .75.324.75.749 0 .193-.073.385-.219.532l-5.72 5.719 5.719 5.719c.147.147.22.339.22.531 0 .427-.349.75-.75.75-.192 0-.385-.073-.531-.219l-5.719-5.719-5.719 5.719c-.146.146-.339.219-.531.219-.401 0-.75-.323-.75-.75 0-.192.073-.384.22-.531l5.719-5.719-5.72-5.719c-.146-.147-.219-.339-.219-.532 0-.425.346-.749.75-.749.192 0 .385.073.531.219z"/></svg>
							</div>
							<input type="text" placeholder="cerca..." name="s">
							<span class="my-search-icon">
								<svg width="24" height="24" fill="#fff" xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" clip-rule="evenodd"><path d="M15.853 16.56c-1.683 1.517-3.911 2.44-6.353 2.44-5.243 0-9.5-4.257-9.5-9.5s4.257-9.5 9.5-9.5 9.5 4.257 9.5 9.5c0 2.442-.923 4.67-2.44 6.353l7.44 7.44-.707.707-7.44-7.44zm-6.353-15.56c4.691 0 8.5 3.809 8.5 8.5s-3.809 8.5-8.5 8.5-8.5-3.809-8.5-8.5 3.809-8.5 8.5-8.5z"/></svg>
							</span>
							<!-- results -->
							<div class="results-search pt-4 px-1 d-flex justify-content-center"></div>
						</div>
					</div>
				</div>';



	// items Menù
	$links = wp_get_nav_menu_items('mainThememenu');
	$_linkMob = '';
	$_linkDesk = '';
	$ind = 1;
	$uploaddir = wp_get_upload_dir()['baseurl'];
	$homeurl = get_home_url();



	

	$fieldD = get_term_meta(3, 'posizione_voci_menu')[0];
	$posD = '';
	switch($fieldD) {
		case 'center':
			$posD = 'justify-content-center';
			break;
		case 'end':
			$posD = 'justify-content-end';
			break;
	}


	if($links) {
		$_linkMob .= '<li class="nav-item bdr-y '. $posM .'">
							<a href="'. $homeurl .'"><img src="'. $uploaddir .'/2025/08/ermiLogo.png" width="120" class="pt-3 pb-5"></a>
					</li>';
		foreach ($links as $link) {
			
			
			
			$_linkMob .= '<li class="nav-item bdr-y"><a class="nav-link text-white p-0 py-2 fs-2 '. $posM .'" aria-current="page" href="'.$link->url.'">'.$link->title.'</a></li>';
			
			$_linkDesk .= '<li class="nav-item '.($ind<count($links)?"me-3":"").'"><a class="nav-link text-secondary" aria-current="page" href="'.$link->url.'">'.$link->title.'</a></li>';
			$ind++;
		}
	}
?>


	<header class="site-header h-sticky position-sticky p-0" itemscope="" itemtype="https://schema.org/WPHeader">

			<div class="my-header d-flex align-items-center justify-content-between position-relative">
				<div class="logo col-6 col-md-1 p-2">
					
					<a href="<?= $homeurl ?>"><img src="<?= $uploaddir ?>/2025/08/ermiLogo.png"></a>
				</div>
				<?= $modal ?>
				<!-- MOBILE -->
				<div class="menu-mobile d-flex d-xl-none justify-content-end text-white col-6">
					<button class="hamburger hamburger--emphatic-r position-relative bg-white z-1" type="button">
						<span class="hamburger-box">
							<span class="hamburger-inner">
								<span></span>
							</span>
						</span>
					</button>
					<div class="my-nav-mobile pt-5 position-absolute bg-secondary">
						<div class="links-m-box pt-5">
							<?= $_linkMob ?>
						</div>

						<!-- button active search -->
						<?= $searchM ?>

					</div>
				</div>


				<!-- DESKTOP -->
				<div class="menu-desktop d-none d-xl-flex col-xl-11 py-3">
					<div class="my-nav col-11 text-end">
						<ul class="mb-0 d-flex align-items-center <?= $posD ?>">
							<?= $_linkDesk ?>
						</ul>
					</div>	

					<!-- button active search -->
					<?= $searchD ?>

				</div>
			</div>

	</header>


<?php
/**
 * Fires immediately after the `genesis_header` action hook, before the site inner opening markup.
 *
 * @since 1.0.0
 */
do_action( 'genesis_after_header' );

genesis_markup(
	[
		'open'    => '<div %s>',
		'context' => 'site-inner',
	]
);
genesis_structural_wrap( 'site-inner' );


            